### ISSUE TITLE
Country recognition ip address does no longer work

### ISSUE THREAD

**Issue by KloonDuino** [tawk/tawk-wordpress#1]
Since a few days the Dashboard can no longer tell me from what country a visitor came. Around 50% is displaying wrong information now.
Strange thing is that reverse dns still works. So many times a country of  'unknown' comes up, while the rdns states a Dutch domain name (or other countries name).

We need this functionality to function properly because we only do business with people from the Netherlands. We use a trigger to send a warning to people from other countries.

![](https://i.imgsafe.org/93302ce774.png)

(
Please don't tell me that all of a sudden 50% of our customers are using a vpn to visit our site (as your help desk tried to convince us).
)

**Comment by mikebrownvb** [comment]
Hello,

Has this issue been addressed?

It is helpful for issues like this to receive a response. 

When left unanswered it looks unprofessional and is not helpful for those of us who are trying to make a decision on what chat software to use.

Thanks,
Mike

**Comment by robdas** [comment]
Hi Mike,

This issue was resolved many iterations ago - my apologies for not responding to the thread.

Cheers,

Robert
![screen shot 2017-01-20 at 7 40 31 am](https://cloud.githubusercontent.com/assets/9743914/22137436/c2313f0e-dee3-11e6-8b42-822d14176387.png)

**Comment by mikebrownvb** [comment]
Hello Robert,

Glad to hear this issue was resolved.

Thank you for the response. By the way I installed Tawk.to on my WordPress blog and the features and functionality are so far amazing. 

Thanks,
Mike
